---
- name: "SECTION 09: Capture Cluster Status Snapshot"
  when: is_active_node | bool
  block:
    - name: Get Final Cluster Status
      command: pcs status
      register: final_cluster_status
      changed_when: false
      ignore_errors: true

    - name: Save Status Snapshot
      ansible.builtin.set_fact:
        cluster_status_output: "{{ final_cluster_status.stdout | default('Error: Unable to retrieve cluster status.') }}"
